version: '3.4'

services:
  eventmanagement.api:
    image: ${DOCKER_REGISTRY-}eventmanagementapi
    build:
      context: .
      dockerfile: EventManagement.API/Dockerfile
    depends_on: [ mssql ]
    ports:
        - "8000:80"
        - "8001:443"
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
       # ASPNETCORE_HTTPS_PORT: "8081"
        ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    networks:
        - em-system-network

  emseq:
    image: datalust/seq
    restart: unless-stopped 
    ports:
        - 5341:80
    environment:
         - ACCEPT_EULA=Y
    networks:
        - em-system-network

  mssql: 
    build:
        context: .
        dockerfile: sql.Dockerfile
    restart: always
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password_123BD
    user: root
    ports: 
      - "1440:1433"
    #volumes: 
    #  - "sqldata:/var/opt/mssql"
    networks:
        - em-system-network



networks:
  em-system-network: {}

#volumes: 
#  sqldata: