
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x 
      - name: Restore dependencies
        run: dotnet restore EventManagement.API/
      - name: Build
        run: dotnet build EventManagement.API/ --no-restore
      - name: Test
        run: dotnet test Tests/Application.UnitTests/
   
        
