
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x 
      - name: Restore dependencies
        run: dotnet restore EventManagement.API/EventManagement.API.sln
      - name: Build
        run: dotnet build EventManagement.API/EventManagement.API.sln --no-restore
      - name: Test
        run: dotnet test Tests/Application.UnitTests/
      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.5.1
        with:
          install: sqlengine, sqlclient, sqlpackage, localdb
      - name: Build the Docker image
        run: |
          cd EventManagement.API/
          docker build -t emmsqltest -f sql.Dockerfile .
      - name: up container
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Password_123BD" "MSSQL_PID=Developer" -p 1440:1433 -u root -S localhost -d emmsqltest
      - name: Integration test
        env:
          DefaultConnection: Server=localhost,1440;Database=EventManagementTests;User Id=sa;Password=Password_123BD;
        run: dotnet test Tests/EM.IntegrationTests/
   
        
